name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
      
    - name: Generate output
      run: |
        echo "<!DOCTYPE html>" > index.html
        echo "<html><head><title>DIP Demo</title></head>" >> index.html
        echo "<body><h1>Dependency Inversion Principle Demo</h1>" >> index.html
        echo "<h2>Última ejecución: $(TZ='America/Lima' date +'%d/%m/%Y %H:%M:%S %Z')</h2>" >> index.html
        echo "<pre>" >> index.html
        node index.js >> index.html
        echo "</pre></body></html>" >> index.html
        
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        force_orphan: true