name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permisos necesarios para GITHUB_TOKEN
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Generate fresh HTML with Peru time
      run: |
        # Obtener fecha/hora exacta de Perú
        PERU_TIME=$(TZ='America/Lima' date +'%A %d de %B del %Y a las %H:%M:%S (%Z)')
        
        # Crear archivo HTML completamente nuevo
        cat <<EOF > index.html
        <!DOCTYPE html>
        <html lang="es">
        <head>
            <meta charset="UTF-8">
            <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
            <meta http-equiv="Pragma" content="no-cache">
            <meta http-equiv="Expires" content="0">
            <title>DIP Demo - ${PERU_TIME}</title>
        </head>
        <body>
            <h1>Dependency Inversion Principle Demo</h1>
            <h2>Última ejecución: ${PERU_TIME}</h2>
            <pre>
        $(node index.js)
            </pre>
        </body>
        </html>
        EOF
        
    - name: Wipe and Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        force_orphan: true
        keep_files: false