name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Generate fresh HTML with Peru time
      run: |
        # 1. Crear directorio limpio
        rm -rf ./gh-pages-content
        mkdir -p ./gh-pages-content

        # 2. Generar HTML con hora exacta de Perú
        PERU_TIME=$(TZ='America/Lima' date +'%d/%m/%Y %H:%M:%S %Z')
        
        cat <<EOF > ./gh-pages-content/index.html
        <!DOCTYPE html>
        <html>
        <head>
            <title>DIP Demo - ${PERU_TIME}</title>
            <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
            <meta http-equiv="Pragma" content="no-cache">
            <meta http-equiv="Expires" content="0">
        </head>
        <body>
            <h1>Última ejecución: ${PERU_TIME}</h1>
            <pre>$(node index.js)</pre>
        </body>
        </html>
        EOF

    - name: Wipe and Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: gh-pages-content
        clean: true
        clean-exclude: |
          .git
          .nojekyll
        single-commit: true