name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necesario para GITHUB_TOKEN
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
      
    - name: Generate output with Peru time
      run: |
        # Generar contenido con marca de tiempo única
        TIMESTAMP=$(TZ='America/Lima' date +'%s')
        echo "<!DOCTYPE html>" > index.html
        echo "<html><head>" >> index.html
        echo "<title>DIP Demo</title>" >> index.html
        echo "<meta http-equiv='Cache-Control' content='no-cache, no-store, must-revalidate'>" >> index.html
        echo "<meta http-equiv='Pragma' content='no-cache'>" >> index.html
        echo "<meta http-equiv='Expires' content='0'>" >> index.html
        echo "</head><body>" >> index.html
        echo "<h1>Dependency Inversion Principle Demo</h1>" >> index.html
        echo "<h2>Última ejecución: $(TZ='America/Lima' date +'%A %d de %B del %Y a las %H:%M:%S %Z')</h2>" >> index.html
        echo "<div hidden>Build ID: ${TIMESTAMP}</div>" >> index.html
        echo "<pre>" >> index.html
        node index.js >> index.html
        echo "</pre></body></html>" >> index.html
        
    - name: Deploy with forced update
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        force_orphan: true
        user_name: 'GitHub Actions'
        user_email: '41898282+github-actions[bot]@users.noreply.github.com'